# Generated by Django 5.1.3 on 2024-11-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_account_first_name_account_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
    ]
