# Generated by Django 5.1.3 on 2024-11-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_account_address_account_city_account_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='zipcode',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
    ]
