# Generated by Django 5.1.3 on 2024-11-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0010_rename_total_invest_balance_dashboard_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='deposit_wallet_balance',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='interest_wallet_balance',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='referral_balance',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='referral_code',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_deposit',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_invest_balance',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='total_withdraw',
            field=models.IntegerField(default=0.0),
        ),
    ]
