# Generated by Django 5.1.3 on 2024-11-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0012_dashboard_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='histotry',
            name='wallet_Address',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
