# Generated by Django 5.1.3 on 2024-11-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0015_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='cryptomus_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='wallet_Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
